config/routes.rb
Rails.application.routes.draw do
  root 'user/members#index'

  get 'admin', to: 'backoffice/dashboard#index'

  namespace :user do
    resources :members, only: [:index]
    resources :advertisings, only: [:show]
  end

  namespace :backoffice do
    resources :categories, except: %i[show destroy]
    resources :admins, except: [:show]
    resources :members, except: [:show]
    resources :clients, except: %i[show destroy]
    resources :weathers, except: %i[show destroy]
    resources :advertisings, except: [:show]
    resources :qrcodes, except: [:show]
    resources :coupons, except: %i[show destroy]
    get 'generate_qr/:id', to: 'qrcodes#generate', as: 'generate'
    get 'download/:id', to: 'qrcodes#download', as: 'qr_code'
    get 'dashboard', to: 'dashboard#index'
  end

  devise_for :admins, skip: [:registration]
  devise_for :members, skip: [:registration]

end

app/controllers/backoffice/admins_controller.rb
# frozen_string_literal: true

module Backoffice
  class AdminsController < BackofficeController

    before_action :set_admin, only: %i[edit update destroy]
    after_action :verify_authorized, only: :new
    after_action :verify_policy_scoped, only: :index

    def index
      @admins = policy_scope(Admin)
    end

    def new
      @admin = Admin.new
      authorize @admin
    end

    def create
      @admin = AdminService.create(params_admin)

      if @admin.errors.any?
        render :new
      else
        redirect_to backoffice_admins_path, notice: "O Administrador #{@admin.email} foi salvo com sucesso"
      end
    end

    def edit; end

    def update
      passwd = params[:admin][:password]
      passwd_conf = params[:admin][:password_confirmation]

      if passwd.blank? && passwd_conf.blank?
        params[:admin].delete(:password)
        params[:admin].delete(:password_confirmation)
      end

      if @admin.update(params_admin)
        redirect_to backoffice_admins_path, notice: "O Administrador #{@admin.name} foi atualizado com sucesso"
      else
        render :new
      end
    end

    def destroy
      admin_name = @admin.name

      if @admin.destroy
        redirect_to backoffice_admins_path, notice: "O administrador #{admin_name} foi excluído com sucesso"
      else
        render :index
      end
    end

    private
    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      if @admin.blank?
        params.require(:admin).permit(:name, :email, :password, :password_confirmation, :role)
      else
        params.require(:admin).permit(policy(@admin).permitted_attributes)
      end
    end

  end
end

app/controllers/backoffice/admins_controller/admin_service.rb
# frozen_string_literal: true

module Backoffice
  module AdminsController
    class AdminService

      attr_accessor :admin

      def self.create(params_admin)
        @admin = Admin.new(params_admin)

        @admin.save! if @admin.valid?

        @admin
      end

    end
  end
end

app/controllers/backoffice/advertisings_controller.rb
# frozen_string_literal: true

module Backoffice
  class AdvertisingsController < BackofficeController

    before_action :set_advertising, only: %i[edit update destroy]
    before_action :set_category, only: %i[new edit]
    before_action :set_weather, only: %i[new edit]
    before_action :set_qrcode, only: %i[new edit]
    before_action :set_client, only: %i[new edit]

    def index
      @advertisings = Advertising.includes(:client).all
    end

    def new
      @advertising = Advertising.new
    end

    def create
      @advertising = AdvertisingService.create(params_advertising)

      if @advertising.errors.any?
        render :new
      else
        redirect_to backoffice_advertisings_path, notice: "#{@advertising.client.name} foi salvo com sucesso"
      end
    end

    def edit; end

    def update
      if @advertising.update(params_advertising)
        redirect_to backoffice_advertisings_path, notice: "#{@advertising.client.name} foi atualizado com sucesso"
      else
        render :new
      end
    end

    def destroy
      adv_cli = @advertising.client.name

      if @advertising.destroy
        redirect_to backoffice_advertisings_path, notice: "O anúncio (#{adv_cli}) foi excluído com sucesso"
      else
        render :index
      end
    end

    private
    def set_advertising
      @advertising = Advertising.find(params[:id])
    end

    def set_category
      @categories_for_advertising = Category.all
    end

    def set_weather
      @weather_for_advertising = Weather.all
    end

    def set_qrcode
      @qrcode_for_advertising = Qrcode.all
    end

    def set_client
      @client_for_advertising = Client.all
    end

    def params_advertising
      params.require(:advertising).permit(:start_date, :end_date, :picture,
                                          :category_id, :weather_id, :qrcode_id,
                                          :client_id)
    end

  end
end

app/controllers/backoffice/advertisings_controller/advertising_service.rb
# frozen_string_literal: true

module Backoffice
  module AdvertisingsController
    class AdvertisingService

      attr_accessor :advertising

      def self.create(params_advertising)
        @advertising = Advertising.new(params_advertising)

        @advertising.save! if @advertising.valid?

        @advertising
      end

    end
  end
end

app/controllers/backoffice/categories_controller.rb
# frozen_string_literal: true

module Backoffice
  class CategoriesController < BackofficeController

    before_action :set_category, only: %i[edit update]

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = CategoryService.create(params_category)

      if @category.errors.any?
        render :new
      else
        redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) salva com sucesso"
      end
    end

    def edit; end

    def update
      if @category.update(params_category)
        redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) atualizada com sucesso"
      else
        render :new
      end
    end

    private
    def set_category
      @category = Category.find(params[:id])
    end

    def params_category
      params.require(:category).permit(:description)
    end

  end
end

app/controllers/backoffice/categories_controller/category_service.rb
# frozen_string_literal: true

module Backoffice
  module CategoriesController
    class CategoryService

      attr_accessor :category

      def self.create(params_category)
        @category = Category.new(params_category)

        @category.save! if @category.valid?

        @category
      end

    end
  end
end

app/controllers/backoffice/clients_controller.rb
# frozen_string_literal: true

module Backoffice
  class ClientsController < BackofficeController

    before_action :set_client, only: %i[edit update]

    def index
      @clients = Client.all
    end

    def new
      @client = Client.new
    end

    def create
      @client = ClientService.create(params_client)

      if @client.errors.any?
        render :new
      else
        redirect_to backoffice_clients_path, notice: "O Cliente (#{@client.name}) foi salvo com sucesso"
      end
    end

    def edit; end

    def update
      if @client.update(params_client)
        redirect_to backoffice_clients_path, notice: "O Cliente (#{@client.name}) foi atualizado com sucesso"
      else
        render :new
      end
    end

    private
    def set_client
      @client = Client.find(params[:id])
    end

    def params_client
      params.require(:client).permit(:name, :millisec)
    end

  end
end

app/controllers/backoffice/clients_controller/client_service.rb
# frozen_string_literal: true

module Backoffice
  module ClientsController
    class ClientService

      attr_accessor :client

      def self.create(params_client)
        @client = Client.new(params_client)

        @client.save! if @client.valid?

        @client
      end

    end
  end
end

app/controllers/backoffice/coupons_controller.rb
# frozen_string_literal: true

module Backoffice
  class CouponsController < BackofficeController

    before_action :set_coupon, only: %i[edit update]

    def index
      @coupons = Coupon.all
    end

    def edit; end

    def update
      if @coupon.update(params_coupon)
        redirect_to backoffice_coupons_path, notice: "O Cupom de (#{@coupon.name}) foi baixado com sucesso"
      else
        render :new
      end
    end

    private
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    def params_coupon
      params.require(:coupon).permit(:status)
    end

  end
end

app/controllers/backoffice/dashboard_controller.rb
# frozen_string_literal: true

module Backoffice
  class DashboardController < BackofficeController

    def index; end

  end
end

app/controllers/backoffice/members_controller.rb
# frozen_string_literal: true

module Backoffice
  class MembersController < BackofficeController

    before_action :set_member, only: %i[edit update destroy]

    def index
      @members = Member.all
    end

    def new
      @member = Member.new
    end

    def create
      @member = MemberService.create(params_member)

      if @member.errors.any?
        render :new
      else
        redirect_to backoffice_members_path, notice: "O Membro #{@member.name} foi salvo com sucesso"
      end
    end

    def edit; end

    def update
      passwd = params[:member][:password]
      passwd_conf = params[:member][:password_confirmation]

      if passwd.blank? && passwd_conf.blank?
        params[:member].delete(:password)
        params[:member].delete(:password_confirmation)
      end

      if @member.update(params_member)
        redirect_to backoffice_members_path, notice: "O Membro #{@member.name} foi atualizado com sucesso"
      else
        render :new
      end
    end

    def destroy
      member_name = @member.name

      if @member.destroy
        redirect_to backoffice_members_path, notice: "O Membro #{member_name} foi excluído com sucesso"
      else
        render :index
      end
    end

    private
    def set_member
      @member = Member.find(params[:id])
    end

    def params_member
      params.require(:member).permit(:name, :email, :password, :password_confirmation)
    end

  end
end

app/controllers/backoffice/members_controller/member_service.rb
# frozen_string_literal: true

module Backoffice
  module MembersController
    class MemberService

      attr_accessor :member

      def self.create(params_member)
        @member = Member.new(params_member)

        @member.save! if @member.valid?

        @member
      end

    end
  end
end

app/controllers/backoffice/qrcodes_controller.rb
# frozen_string_literal: true

module Backoffice
  class QrcodesController < BackofficeController

    require 'rqrcode_png'
    before_action :set_qrcode, only: %i[edit update destroy generate download]

    def index
      @qrcodes = Qrcode.all
    end

    def new
      @qrcode = Qrcode.new
    end

    def create
      @qrcode = QrcodeService.create(params_qrcode)

      if @qrcode.errors.any?
        render :new
      else
        redirect_to edit_backoffice_qrcode_path(@qrcode.id), notice: 'Salvo com sucesso!'
      end
    end

    def edit; end

    def update
      if @qrcode.update(params_qrcode)
        redirect_to backoffice_qrcodes_path, notice: 'O Cupom foi atualizado com sucesso'
      else
        render :new
      end
    end

    def destroy
      client_name = @qrcode.client

      if @qrcode.destroy
        redirect_to backoffice_qrcodes_path, notice: "O cupom de #{client_name} foi excluído com sucesso!"
      else
        render :index
      end
    end

    def generate
      generate_qrcode
      redirect_to edit_backoffice_qrcode_path(@qrcode.id)
    end

    def download
      send_file "#{Rails.root}/public#{@qrcode.img_path}",
                filename: 'qrcode.png',
                type: 'image/png'
    end

    private
    def set_qrcode
      @qrcode = Qrcode.find(params[:id])
    end

    def params_qrcode
      params.require(:qrcode).permit(:date_time, :validity, :value, :client, :img_path, :token)
    end

    def generate_qrcode
      img_show = "/qrcodes/#{DateTime.now}.png"
      img_path = "public#{img_show}"
      @qr = RQRCode::QRCode.new(@qrcode.token, size: 10)
      png = @qr.to_img
      png.resize(300, 300).save(img_path)
      @qrcode.update(img_path: img_show)
    end

  end
end

app/controllers/backoffice/qrcodes_controller/qrcode_service.rb
# frozen_string_literal: true

module Backoffice
  class QrcodesController::QrcodeService

    attr_accessor :qrcode

    def self.create(params_qrcode)
      @qrcode = Qrcode.new(params_qrcode)

      @qrcode.save! if @qrcode.valid?

      @qrcode
    end

  end
end

app/controllers/backoffice/weathers_controller.rb
# frozen_string_literal: true

module Backoffice
  class WeathersController < BackofficeController

    before_action :set_weather, only: %i[edit update]

    def index
      @weathers = Weather.all
    end

    def new
      @weather = Weather.new
    end

    def create
      @weather = WeatherService.create(params_weather)

      if @weather.errors.any?
        render :new
      else
        redirect_to backoffice_weathers_path, notice: "O clima #{@weather.description} foi salvo com sucesso!"
      end
    end

    def edit; end

    def update
      if @weather.update(params_weather)
        redirect_to backoffice_weathers_path, notice: "O clima #{@weather.description} foi atualizado com sucesso!"
      else
        render :new
      end
    end

    private
    def set_weather
      @weather = Weather.find(params[:id])
    end

    def params_weather
      params.require(:weather).permit(:description, :min_temp, :max_temp)
    end

  end
end

app/controllers/backoffice/weathers_controller/weather_service.rb
# frozen_string_literal: true

module Backoffice
  module WeathersController
    class WeatherService

      attr_accessor :weather

      def self.create(params_weather)
        @weather = Weather.new(params_weather)

        @weather.save! if @weather.valid?

        @weather
      end

    end
  end
end

app/controllers/backoffice_controller.rb
# frozen_string_literal: true

class BackofficeController < ApplicationController

  before_action :authenticate_admin!
  layout 'backoffice'

end

app/helpers/backoffice/admins_helper.rb
# frozen_string_literal: true

module Backoffice
  module AdminsHelper

    OptionsForRoles = Struct.new(:id, :description)

    def options_for_roles
      Admin.roles_i18n.map do |key, value|
        OptionsForRoles.new(key, value)
      end
    end

  end
end

app/helpers/backoffice/advertisings_helper.rb
# frozen_string_literal: true

module Backoffice
  module AdvertisingsHelper
  end
end

app/helpers/backoffice/categories_helper.rb
# frozen_string_literal: true

module Backoffice
  module CategoriesHelper
  end
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form",
           locals: {action: "Editando Administrador"} %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header"><%= t('labels.admins') %></h1>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">

            <div class="panel-heading">
                <%= t('labels.listing_admins') %>
                <% if policy(@admins).new?%>
                  <%= link_to new_backoffice_admin_path,
                  class:"btn btn-success btn-success-adjust btn-circle pull-right" do%>
                  <i class="fa fa-plus"></i>
                  <% end %>
                <% end %>
            </div>

            <div class="panel-body">
                <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                  <div class="row">
                    <div class="col-sm-12">

                      <table width="100%"
                      class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline"
                      id="indexTable">

                        <thead>
                          <tr role="row">
                            <th class="sorting_asc">#</th>
                            <th class="sorting_asc"><%= t('labels.description') %></th>
                            <th class="sorting_asc"><%= t('labels.name') %></th>
                            <th class="sorting_asc"><%= t('labels.role_access') %></th>
                            <th><%= t('labels.edit') %></th>
                            <th><%= t('labels.delete') %></th>
                          </tr>
                        </thead>

                        <tbody>
                          <% @admins.each do |admin|%>
                            <tr class="gradeA odd" role="row">

                              <td class="sorting_1"><%= admin.id%></td>

                              <td class="sorting_1"><%= admin.name%></td>

                              <td><%= admin.email%></td>

                              <td><%= admin.role_i18n%></td>

                              <td class="option-btn">
                                <%= link_to edit_backoffice_admin_path(admin),
                                  class:"btn btn-primary btn-circle" do%>
                                  <i class="fa fa-edit"></i>
                                <% end %>
                              </td>
                                
                                <td class="option-btn">
                                <% if current_admin.id != admin.id %>
                                  <%= link_to backoffice_admin_path(admin),
                                      method: :delete, class:"btn btn-danger btn-circle",
                                      data:{confirm:t('messages.confirm_with',
                                      item: admin.name)} do%>
                                    <i class="fa fa-times"></i>
                                  <% end %>

                                <% else %>
                                  <button type="button", disabled="disabled",
                                        class="btn btn-danger btn-circle">
                                    <i class="fa fa-times"></i>
                                  </button>
                                <% end %>

                              </td>

                            </tr>
                          <% end %>
                        </tbody>

                      </table>

                    </div>
                  </div>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- FIM DATA TABLE -->

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form",
           locals: {action: "Novo Administrador"} %>