config/routes.rb
Rails.application.routes.draw do
  root 'user/members#index'

  get 'admin', to: 'backoffice/dashboard#index'

  namespace :user do
    resources :members, only: [:index]
    resources :advertisings, only: [:show]
  end

  namespace :backoffice do
    resources :categories, except: %i[show destroy]
    resources :admins, except: [:show]
    resources :members, except: [:show]
    resources :clients, except: %i[show destroy]
    resources :weathers, except: %i[show destroy]
    resources :advertisings, except: [:show]
    resources :qrcodes, except: [:show]
    resources :coupons, except: %i[show destroy]
    get 'generate_qr/:id', to: 'qrcodes#generate', as: 'generate'
    get 'download/:id', to: 'qrcodes#download', as: 'qr_code'
    get 'dashboard', to: 'dashboard#index'
  end

  devise_for :admins, skip: [:registration]
  devise_for :members, skip: [:registration]

end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord

  # Constants
  ROLES = { full_access: 0, restricted_access: 1 }.freeze
  # Enums
  enum role: ROLES

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/advertising.rb
# frozen_string_literal: true

class Advertising < ApplicationRecord

  belongs_to :category
  belongs_to :weather
  belongs_to :qrcode
  belongs_to :client, counter_cache: true

  validates :picture, presence: true

  has_attached_file :picture,
                    url: '/system/:attachment/:id/:style/:filename',
                    path: ':rails_root/public/system/:attachment/:id/:style/:filename',
                    storage: :filesystem,
                    styles: { large: '1280x720>', thumb: '100x100>' },
                    default_url: '/images/:style/missing.png'

  validates_attachment_content_type :picture, content_type: %r{\Aimage/.*\z}

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord

  # Associations
  has_many :advertisings

  # validations
  validates :description, presence: true

end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord

  # Associations
  has_many :advertisings

end

app/models/coupon.rb
# frozen_string_literal: true

class Coupon < ApplicationRecord
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/qrcode.rb
# frozen_string_literal: true

class Qrcode < ApplicationRecord
end

app/models/weather.rb
# frozen_string_literal: true

class Weather < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

  protected
  def layout_by_resource
    if devise_controller? && resource_name == :admin || resource_name == :member
      'backoffice_devise'
    else
      'application'
    end
  end

  def user_not_authorized
    flash[:alert] = 'Você não está autorizado a executar esta ação'
    redirect_to(request.referer || root_path)
  end

  def pundit_user
    current_admin
  end

end

app/controllers/backoffice_controller.rb
# frozen_string_literal: true

class BackofficeController < ApplicationController

  before_action :authenticate_admin!
  layout 'backoffice'

end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController

  before_action :authenticate_member!
  layout 'user_member'

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
# frozen_string_literal: true

module Backoffice
  module AdminsHelper

    OptionsForRoles = Struct.new(:id, :description)

    def options_for_roles
      Admin.roles_i18n.map do |key, value|
        OptionsForRoles.new(key, value)
      end
    end

  end
end

app/helpers/backoffice/clients_helper.rb
# frozen_string_literal: true

module Backoffice
  module ClientsHelper
  end
end

app/helpers/backoffice/coupons_helper.rb
# frozen_string_literal: true

module Backoffice
  module CouponsHelper
  end
end

app/helpers/backoffice/qrcodes_helper.rb
# frozen_string_literal: true

module Backoffice
  module QrcodesHelper
  end
end

app/helpers/backoffice/weather_helper.rb
# frozen_string_literal: true

module Backoffice
  module WeatherHelper
  end
end

app/helpers/user/advertisings_helper.rb
# frozen_string_literal: true

module User
  module AdvertisingsHelper
  end
end

app/helpers/user/members_helper.rb
# frozen_string_literal: true

module User
  module MembersHelper
  end
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>

<% if @admin.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

    <ul>
      <% @admin.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>

  </div>
<% end %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">

      <div class="panel-heading">
        <%= action %>
      </div>

      <div class="panel-body">
        <div class="col-lg-6">
          <%= form_for([:backoffice, @admin]) do |f| %>
            <div class="form-group">
              <label>Nome</label>
              <%= f.text_field :name, class:"form-control",
              placeholder: t('placeholders.john') %>
            </div>

            <div class="form-group">
              <label>Email</label>
              <%= f.text_field :email, class:"form-control",
              placeholder:t('placeholders.email_address') %>
            </div>

            <div class="form-group">
              <label>Senha</label>
              <%= f.password_field :password, class:"form-control",
              placeholder:t('placeholders.password') %>
            </div>

            <div class="form-group">
              <label>Confirmação da senha</label>
              <%= f.password_field :password_confirmation, class:"form-control",
              placeholder:t("placeholders.confirm_password") %>
            </div>

            <% if policy(@admin).edit?%>
              <div class="from-group">
                <%= f.label :role %>
                <%= f.collection_radio_buttons(:role, options_for_roles, :id,
                                                :description) do |b| %>
                  <div class="radio">
                    <%= b.label {b.radio_button + b.text} %>
                  </div>
                <% end %>
              </div>
            <% end %>

            <button type="submit" class="btn btn-primary"><%= t('buttons.save') %></button>

            <%= link_to backoffice_admins_path,
              class:"btn btn-outline btn-danger" do%>
              <%= t('buttons.cancel') %>
            <% end %>
          <% end %>

        </div>
      </div>

      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-12 -->
</div>